### ISSUE TITLE
Roll-out Dashboard for Document Tracking module

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/Dashboard#1]
Provide Dashboard for document Tracking Module. Following reference to be used for RAG Indicator.

===================================
LatestStatus | With | Indicator | Action   Indicator
===================================
DispatchOfSalesInvoiceDOM | Accounts-Billing | Amber | Accounts Billing has   to Forward to Accounts Payments
ForwardedToAccountsBillingDOM | Accounts-Billing | Red | Accounts Billing has   to Acknowledge Receipt of Document
ReceivedByAccountsBillingFromLogistic | Accounts-Billing | Amber | Accounts Billing has   to Process the IR
ForwardedToAccountsPaymentByAccountsBilling | Accounts-Payments | Red | Accounts Payments has   to Acknowledge Receipt of Document
ForwardedToAccountsPaymentByLogistics | Accounts-Payments | Red | Accounts Payments has   to Acknowledge Receipt of Document
ReceivedByAccountsPaymentFromLogistics | Accounts-Payments | Amber | Accounts Payments has   to Process the IR
ReceivedInAccountsPaymentFromAccountsBilling | Accounts-Payments | Amber | Accounts Payments has   to Process the IR
Free | Material Accounts | Amber | Material Accounts has   to Process the IR
ReturnedByAccountsPaymentToLogistics | Material Accounts | Red | Material Accounts to   Acknowledge the Returned Document
ReturnReceivedByLogisticFromAccountsPMT | Material Accounts | Amber | Material Accounts has   to Process the Returned Document
ReturnReceivedByLogisticsFromAccountsBillingDOM | Material Accounts | Amber | Material Accounts has   to Process the Returned Document
ReturnToLogisticsByAccountsBillingDOM | Material Accounts | Red | Material Accounts to   Acknowledge the Returned Document

**Comment by hariharan-isgec** [comment]
Created Dashboard using below views

RED
SELECT IRNumber,IRNDate,BPName,Project,ReasonDescription,UserName FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_RED
SELECT count(*) as COUNT FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_RED

AMBER
SELECT IRNumber,IRNDate,BPName,Project,ReasonDescription,UserName FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_AMBER
SELECT count(*) as COUNT FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_AMBER

TOTAL
SELECT IRNumber,IRNDate,BPName,Project,ReasonDescription,UserName FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_TOTAL
SELECT count(*) as COUNT FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_TOTAL

GREEN
SELECT 'NA' as COUNT FROM inforerpdb.dbo.LN_DocumentTracking_MATSMD_TOTAL


![image](https://user-images.githubusercontent.com/43699418/49716092-a5a30700-fc78-11e8-8176-fa0eac2845e0.png)

**Comment by hariharan-isgec** [comment]
@veena-isgec Create Menu in LN and assign to Material Accounts relevant role for SMD users

**Comment by veena-isgec** [comment]
Delivered to user. Feedback awaited.

![image](https://user-images.githubusercontent.com/43699482/50533629-9fa39600-0b53-11e9-8128-ea3c13eb2c60.png)
